Wolfpack/Wolfpack.Web/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wolfpack.BusinessLayer;
using Wolfpack.BusinessLayer.Extensions;
using Wolfpack.Data;
using Wolfpack.Data.Models;
using Wolfpack.Web.Helpers;
using Wolfpack.Web.Helpers.Enums;
using Wolfpack.Web.Helpers.Interfaces;
using Wolfpack.Web.Models.Event;

namespace Wolfpack.Web.Controllers
{
    public class EventController : BaseController
    {
        public EventController(Context context, IUserHelper userHelper = null, ISessionHelper sessionHelper = null)
            : base(context, userHelper, sessionHelper) { }

        /// <summary>
        /// Show all events of logged-in user
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //Get events started by user
            var user = UserHelper.GetCurrentDbUser(Context);
            return View(new UserEventsVM
            {
                CreatedEvents = Context.Events
                    .Where(x => x.EventCreator.Id == user.Id)
                    .Select(e => new EventVM
                    {
                        Id = e.Id,
                        CreatedOn = e.CreatedOn,
                        EventName = e.EventName
                    }),
                ParticipatingEvents = user.EventTeams
                    .Select(e => new EventVM
                    {
                        Id = e.Event.Id,
                        CreatedOn = e.Event.CreatedOn,
                        EventName = e.Event.EventName
                    })
            });
        }

        /// <summary>
        /// View single event
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            var userId = UserHelper.GetCurrentUser().Id;
            var singleEvent = Context.Events.SingleOrDefault(x => x.Id == id);
            if (singleEvent != null)
            {
                var skills = singleEvent.Skills.Select(s => new SkillVM
                {
                    Description = s.Description,
                    Id = s.Id,
                    Name = s.Name
                });

                var teams = singleEvent.Teams.Select(t => new TeamVM
                {
                    Users = t.Users.Select(u => new UserVM
                    {
                        FirstName = u.FirstName,
                        Id = u.Id,
                        LastName = u.LastName,
                        UserName = u.UserName
                    }),
                    Name = t.Name,
                    Id = t.Id,
                });

                return View(new EventVM
                {
                    CreatedOn = singleEvent.CreatedOn,
                    EventCreator = singleEvent.EventCreator.Id,
                    EventName = singleEvent.EventName,
                    GroupId = singleEvent.Group.Id,
                    Id = singleEvent.Id,
                    Skills = skills,
                    Teams = teams,
                    IsEventCreator = singleEvent.EventCreator.Id == userId
                });
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// View edit
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult Edit(int Id)
        {
            return View(new EditVM { Id = Id });
        }

        /// <summary>
        /// Form for deleting event
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            //TODO: Add actual deletion after post [HttpDelete]? Dont forget to remove all items that depend on an event
            int loggedInUserId = UserHelper.GetCurrentUser().Id;
            var singleEvent = Context.Events.SingleOrDefault(x => x.Id == id && x.EventCreator.Id == loggedInUserId);
            if (singleEvent != null)
            {
                return View(new EventVM
                {
                    EventName = singleEvent.EventName,
                    CreatedOn = singleEvent.CreatedOn
                });
            }
            return RedirectToAction("Index");
        }

        public ActionResult Team(int id)
        {
            var team = Context.EventTeams.GetById(id);
            var vm = new TeamVM
            {
                Name = team.Name,
                Users = team.Users.Select(u => new UserVM
                {
                    FirstName = u.FirstName,
                    Id = u.Id,
                    LastName = u.LastName,
                    UserName = u.UserName,
                    SkillRatings = u.UserSkills.Select(us => new SkillRatingVM
                    {
                        Rating = us.Ratings.Average(r => r.Mark),
                        Name = us.Skill.Name
                    })
                }),
                //SkillNames = team.Event.Skills.Select(s => s.Name) TODO: Only get skills from event not all in users
            };

            vm.SkillNames = vm.Users.First().SkillRatings.Select(x => x.Name).ToList();

            return View(vm);
        }

        /// <summary>
        /// View for generating teams
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult GenerateTeams(int Id)
        {
            var selectListItems = new List<SelectListItem>();

            foreach (var item in Enum.GetValues(typeof(AlgorithmType)))
            {
                selectListItems.Add(new SelectListItem { Value = item.ToString(), Text = item.ToString() });
            }

            return View("GenerateTeamsForm", new GenerateTeamsVM
            {
                EventId = Id,
                AlgorithmTypes = selectListItems,
                AlgorithmType = AlgorithmType.AverageTeams
            });
        }

        public ActionResult RateTeamMembers(int id )
        {
            return View( new { Id = id });
        }

        [HttpPost]
        public ActionResult GenerateTeams(GenerateTeamsVM vm)
        {
            if (vm.TeamSize < 1)
            {
                vm.Message = "Please make sure you have filled in a max team size";
                return View("GenerateTeamsForm", vm);
            }

            var currentEvent = Context.Events.GetById(vm.EventId);

            switch (vm.AlgorithmType)
            {
                case AlgorithmType.AverageTeams:
                    _generateAverageTeams(currentEvent, vm.TeamSize);
                    break;
                case AlgorithmType.BestTeam:
                    _generateBestTeams(currentEvent, vm.TeamSize);
                    break;
                default:
                    return HttpNotFound();
            }

            foreach (var user in currentEvent.Group.Users)
            {
                user.Notifications.Add(new Notification
                {
                    Title = "Added to eventTeam for event: " + currentEvent.EventName,
                    Content = $"An event has started and you've been added to a team. " +
                            $"You can now rate your team members through the following link: " +
                            Url.Action("RateUser", "Group", new { id = currentEvent.Group.Id }, this.Request.Url.Scheme),
                    Date = DateTime.Now,
                    IsRead = false
                });
            }

            return RedirectToAction("Details", new { id = vm.EventId });
        }

        private void _generateAverageTeams(Event currentEvent, int teamSize)
        {
            currentEvent.Teams.Clear();

            if (currentEvent != null && !currentEvent.Group.Archived)
            {
                var groupUsers = currentEvent.Group.Users;

                var amountOfTeams = groupUsers.Count / teamSize; 

                for (int i = 0; i < amountOfTeams; i++)
                {
                    var team = new EventTeam { Name = $"{currentEvent.EventName}-Team {i + 1}" };

                    for (int j = 0; j < teamSize; j++)
                    {
                        if (team.Users.Count > 0)
                        {
                            var usersWithoutOpposite = team.Users.Where(u => !team.Users.Any(x => x != null && u != null && x != u && u.GetBestSkill() == x.GetWorstSkill()));

                            if (usersWithoutOpposite != null && usersWithoutOpposite.Count() > 0)
                            {
                                var user = usersWithoutOpposite.Last();
                                var oppositeUser = groupUsers.Where(u => u != null && user != null && !currentEvent.Teams.Any(t => t.Users.Contains(u))
                                    && !team.Users.Contains(u) && u.GetWorstSkill().Id == user.GetBestSkill().Id).FirstOrDefault();

                                if (oppositeUser != null)
                                {
                                    team.Users.Add(oppositeUser);
                                    continue;
                                }
                            }
                        }

                        team.Users.Add(groupUsers.FirstOrDefault(u => !currentEvent.Teams.Any(t => t.Users.Contains(u)) && !team.Users.Contains(u)));
                        continue;
                    }

                    currentEvent.Teams.Add(team);
                }

                var teamsToChange = GetTeamsToChange(currentEvent);

                while (teamsToChange != null && teamsToChange.Count() > 1)
                {
                    var skillToSwitch = teamsToChange.Select(t => new
                    {
                        Team = t,
                        Skill = t.GetTotalsPerSkill().OrderByDescending(x => x.Value).FirstOrDefault().Key
                    });

Wolfpack/Wolfpack.Web/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wolfpack.BusinessLayer.Extensions;
using Wolfpack.Data;
using Wolfpack.Data.Models;
using Wolfpack.Web.Helpers;
using Wolfpack.Web.Helpers.Interfaces;
using Wolfpack.Web.Models.Profile;

namespace Wolfpack.Web.Controllers
{
    public class ProfileController : BaseController
    {
        public ProfileController(Context context, IUserHelper userHelper = null, ISessionHelper sessionHelper = null)
            : base(context, userHelper, sessionHelper) { }

        public ActionResult Index(int? id)
        {
            if (!id.HasValue)
            {
                id = UserHelper.GetCurrentUser().Id;
            }
            var profileVM = new ProfileVM { };
            var user = Context.Users.GetById(id.Value);
            profileVM.Id = user.Id;
            profileVM.UserName = user.UserName;
            profileVM.MemberSince = user.RegisterDate;
            profileVM.Skills = user.UserSkills
                .Select(s => new SkillVM
                {
                    Id = s.Skill.Id,
                    Name = s.Skill.Name,
                    NumberOfRatings = s.Ratings.Count,
                    AverageRating = s.Ratings.Count > 0 ? s.Ratings.Average(r => r.Mark) : 0,
                    Description = s.Skill.Description
                });
            return View(profileVM);
        }

        public ActionResult SearchProfile()
        {
            return View(new SearchVM());
        }

        [HttpPost]
        public ActionResult SearchProfile(SearchVM vm)
        {
            var user = Context.Users.FirstOrDefault(g => g.UserName == vm.UserName);
            //Return a list with possible users if the username is not found.
            if (user == null)
            {
                var possibleUsers = Context.Users.Select(g => new UserVM
                {
                    Id = g.Id,
                    FirstName = g.FirstName,
                    LastName = g.LastName,
                    UserName = g.UserName
                }).Where(g => g.UserName.Contains(vm.UserName));
                return View(new SearchVM { PossibleUsers = possibleUsers });
            }
            else
            {
                return RedirectToAction("Index", new { id = user.Id });
            }
        }

        public ActionResult ViewSkill(int id, int userId)
        {
            var skill = Context.Skills.SingleOrDefault(x => x.Id == id);
            var ratings = Context.Ratings.Where(u => u.UserSkill.User.Id == userId && u.UserSkill.Skill.Id == id).Select(u => new SkillRatingVM
            {
                Rating = u.Mark,
                RatedAt = u.RatedAt,
                Comment = u.Comment
            });

            var finalRatings = new List<SkillRatingVM>();
            var count = 0;
            var totalMark = 0.0;
            foreach(var rating in ratings)
            {
                count++;
                totalMark += rating.Rating;
                finalRatings.Add(new SkillRatingVM
                {
                    AverageMark = Math.Round((totalMark / count), 2),
                    Comment = rating.Comment,
                    Rating = rating.Rating,
                    RatedAt = rating.RatedAt
                });
            }

            var vm = new SingleSkillVM
            {
                Name = skill.Name,
                Description = skill.Description,
                Ratings = finalRatings
            };

            return View(vm);
        }
    }
}

Wolfpack/Wolfpack.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Wolfpack</title>
    <meta name="theme-color" content="#455B65" />
    <link rel="apple-touch-icon" sizes="180x180" href="@Url.Content("~/Content/favicon/apple-touch-icon.png")">
    <link rel="icon" type="image/png" sizes="32x32" href="@Url.Content("~/Content/favicon/favicon-32x32.png")">
    <link rel="icon" type="image/png" sizes="16x16" href="@Url.Content("~/Content/favicon/favicon-16x16.png")">
   
    <link rel="manifest" href="~/Content/favicon/site.webmanifest">
    <link rel="mask-icon" href="~/Content/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="wrapper">
        <div class="mobile-nav">
            <i class="fas fa-bars fa-3x toggle-menu" id="toggle-menu"></i>
        </div>
        <div class="sidebar-wrapper">
            <div class="sidebar" id="sidebar">
                <div class="logo">
                    <img src="~/Content/images/logo.svg" />
                </div>
                <ul class="nav">
                    <li><div id="toggle-collapse"><span>Hide</span><i class="fas fa-bars fa-lg"></i></div></li>
                    <li><a href="@Url.Action("GetNotifications","Notification")"><span>Messages</span><div class="notification-box" id="notification-box"><i class="fas fa-bell fa-lg"></i></div></a></li>
                    <li><a href="@Url.Action("Index","Profile")"><span>Profile</span><i class="fas fa-user-circle fa-lg"></i></a></li>
                    <li><a href="@Url.Action("SearchProfile","Profile")"><span>Users</span><i class="fas fa-user fa-lg"></i></a></li>
                    <li><a href="@Url.Action("Index","Group")"><span>Groups</span><i class="fas fa-users fa-lg"></i></i></a></li>
                    <li><a href="@Url.Action("Index","Event")"><span>Events</span><i class="fas fa-calendar-alt fa-lg"></i></i></a></li>
                    <li><a href="@Url.Action("Index","Dummy")"><span>Dummy</span><i class="fas fa-vial fa-lg"></i></i></a></li>
                </ul>
                <div class="sidebar-bottom">
                    <ul class="nav-bottom">
                        <li><a href="@Url.Action("Logout","Account")"><span>Log out</span><i class="fas fa-sign-out-alt fa-lg"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="main">
            @RenderBody()
        </div>
    </div>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
    <script src="https://cdn.zingchart.com/zingchart.min.js"></script>
    @RenderSection("scripts", required: false)
    <script src="@Url.Content("~/Scripts/main.js")"></script>
    <script>getNotificationCount('@Url.Action("GetNotificationCount", "Notification")')</script>
</body>
</html>

Wolfpack/Wolfpack.Web/Views/Shared/_NoSidebarLayout.cshtml
@{
    Layout = null;
    ViewBag.Title = "Login";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Wolfpack</title>
    <meta name="theme-color" content="#455B65" />
    <link rel="apple-touch-icon" sizes="180x180" href="@Url.Content("~/Content/favicon/apple-touch-icon.png")">
    <link rel="icon" type="image/png" sizes="32x32" href="@Url.Content("~/Content/favicon/favicon-32x32.png")">
    <link rel="icon" type="image/png" sizes="16x16" href="@Url.Content("~/Content/favicon/favicon-16x16.png")">
    <link rel="manifest" href="~/Content/favicon/site.webmanifest">
    <link rel="mask-icon" href="~/Content/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    @Styles.Render("~/Content/css")
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
</head>

<body class="body-form">
<div class="form-wrapper">
    <div class="form-logo">
        <img src="~/Content/images/logo.svg" />
    </div>
    @RenderBody()
</div>
@RenderSection("scripts", required: false)
<script src="@Url.Content("~/Scripts/main.js")"></script>
</body>
</html>